/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApparelRouteImport } from './routes/apparel'
import { Route as CataloguesRouteImport } from './routes/catalogues'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomPatchesRouteImport } from './routes/custom-patches'
import { Route as GlovesRouteImport } from './routes/gloves'
import { Route as MartialArtsCombatSportsRouteImport } from './routes/martial-arts-combat-sports'
import { Route as PaintballRouteImport } from './routes/paintball'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SublimationClothingRouteImport } from './routes/sublimation-clothing'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as ApiKeepaliveRouteImport } from './routes/api/keepalive'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelRoute = ApparelRouteImport.update({
  id: '/apparel',
  path: '/apparel',
  getParentRoute: () => rootRouteImport,
} as any)
const CataloguesRoute = CataloguesRouteImport.update({
  id: '/catalogues',
  path: '/catalogues',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomPatchesRoute = CustomPatchesRouteImport.update({
  id: '/custom-patches',
  path: '/custom-patches',
  getParentRoute: () => rootRouteImport,
} as any)
const GlovesRoute = GlovesRouteImport.update({
  id: '/gloves',
  path: '/gloves',
  getParentRoute: () => rootRouteImport,
} as any)
const MartialArtsCombatSportsRoute = MartialArtsCombatSportsRouteImport.update({
  id: '/martial-arts-combat-sports',
  path: '/martial-arts-combat-sports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintballRoute = PaintballRouteImport.update({
  id: '/paintball',
  path: '/paintball',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SublimationClothingRoute = SublimationClothingRouteImport.update({
  id: '/sublimation-clothing',
  path: '/sublimation-clothing',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepaliveRoute = ApiKeepaliveRouteImport.update({
  id: '/api/keepalive',
  path: '/api/keepalive',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparel': typeof ApparelRoute
  '/catalogues': typeof CataloguesRoute
  '/contact': typeof ContactRoute
  '/custom-patches': typeof CustomPatchesRoute
  '/gloves': typeof GlovesRoute
  '/martial-arts-combat-sports': typeof MartialArtsCombatSportsRoute
  '/paintball': typeof PaintballRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/sublimation-clothing': typeof SublimationClothingRoute
  '/wholesale': typeof WholesaleRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparel': typeof ApparelRoute
  '/catalogues': typeof CataloguesRoute
  '/contact': typeof ContactRoute
  '/custom-patches': typeof CustomPatchesRoute
  '/gloves': typeof GlovesRoute
  '/martial-arts-combat-sports': typeof MartialArtsCombatSportsRoute
  '/paintball': typeof PaintballRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/sublimation-clothing': typeof SublimationClothingRoute
  '/wholesale': typeof WholesaleRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparel': typeof ApparelRoute
  '/catalogues': typeof CataloguesRoute
  '/contact': typeof ContactRoute
  '/custom-patches': typeof CustomPatchesRoute
  '/gloves': typeof GlovesRoute
  '/martial-arts-combat-sports': typeof MartialArtsCombatSportsRoute
  '/paintball': typeof PaintballRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/sublimation-clothing': typeof SublimationClothingRoute
  '/wholesale': typeof WholesaleRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apparel'
    | '/catalogues'
    | '/contact'
    | '/custom-patches'
    | '/gloves'
    | '/martial-arts-combat-sports'
    | '/paintball'
    | '/sitemap.xml'
    | '/studio'
    | '/sublimation-clothing'
    | '/wholesale'
    | '/api/keepalive'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apparel'
    | '/catalogues'
    | '/contact'
    | '/custom-patches'
    | '/gloves'
    | '/martial-arts-combat-sports'
    | '/paintball'
    | '/sitemap.xml'
    | '/studio'
    | '/sublimation-clothing'
    | '/wholesale'
    | '/api/keepalive'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apparel'
    | '/catalogues'
    | '/contact'
    | '/custom-patches'
    | '/gloves'
    | '/martial-arts-combat-sports'
    | '/paintball'
    | '/sitemap.xml'
    | '/studio'
    | '/sublimation-clothing'
    | '/wholesale'
    | '/api/keepalive'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApparelRoute: typeof ApparelRoute
  CataloguesRoute: typeof CataloguesRoute
  ContactRoute: typeof ContactRoute
  CustomPatchesRoute: typeof CustomPatchesRoute
  GlovesRoute: typeof GlovesRoute
  MartialArtsCombatSportsRoute: typeof MartialArtsCombatSportsRoute
  PaintballRoute: typeof PaintballRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  SublimationClothingRoute: typeof SublimationClothingRoute
  WholesaleRoute: typeof WholesaleRoute
  ApiKeepaliveRoute: typeof ApiKeepaliveRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel': {
      id: '/apparel'
      path: '/apparel'
      fullPath: '/apparel'
      preLoaderRoute: typeof ApparelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogues': {
      id: '/catalogues'
      path: '/catalogues'
      fullPath: '/catalogues'
      preLoaderRoute: typeof CataloguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-patches': {
      id: '/custom-patches'
      path: '/custom-patches'
      fullPath: '/custom-patches'
      preLoaderRoute: typeof CustomPatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gloves': {
      id: '/gloves'
      path: '/gloves'
      fullPath: '/gloves'
      preLoaderRoute: typeof GlovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/martial-arts-combat-sports': {
      id: '/martial-arts-combat-sports'
      path: '/martial-arts-combat-sports'
      fullPath: '/martial-arts-combat-sports'
      preLoaderRoute: typeof MartialArtsCombatSportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paintball': {
      id: '/paintball'
      path: '/paintball'
      fullPath: '/paintball'
      preLoaderRoute: typeof PaintballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sublimation-clothing': {
      id: '/sublimation-clothing'
      path: '/sublimation-clothing'
      fullPath: '/sublimation-clothing'
      preLoaderRoute: typeof SublimationClothingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keepalive': {
      id: '/api/keepalive'
      path: '/api/keepalive'
      fullPath: '/api/keepalive'
      preLoaderRoute: typeof ApiKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApparelRoute: ApparelRoute,
  CataloguesRoute: CataloguesRoute,
  ContactRoute: ContactRoute,
  CustomPatchesRoute: CustomPatchesRoute,
  GlovesRoute: GlovesRoute,
  MartialArtsCombatSportsRoute: MartialArtsCombatSportsRoute,
  PaintballRoute: PaintballRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  SublimationClothingRoute: SublimationClothingRoute,
  WholesaleRoute: WholesaleRoute,
  ApiKeepaliveRoute: ApiKeepaliveRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
